const problemDescriptions = {
    // Arrays
    "Largest Element in Array": "Find the maximum element in a given array of size N.<br><br><strong>Example:</strong><pre>Input: arr = [1, 8, 7, 56, 90]\nOutput: 90</pre>",
    "Linear Search": "Given an array, and an element x, find if x is present in the given array or not. If present, return the index, otherwise return -1.<br><br><strong>Example:</strong><pre>Input: arr = [1, 2, 4, 3], x = 4\nOutput: 2</pre>",
    "Two Sum": "Given an array of integers <code>nums</code> and an integer <code>target</code>, return indices of the two numbers such that they add up to <code>target</code>.<br><br>You may assume that each input would have exactly one solution, and you may not use the same element twice.",
    "Remove Duplicates from Sorted Array": "Given an integer array <code>nums</code> sorted in non-decreasing order, remove the duplicates in-place such that each unique element appears only once. The relative order of the elements should be kept the same.",
    "Best Time to Buy and Sell Stock": "You are given an array <code>prices</code> where <code>prices[i]</code> is the price of a given stock on the i-th day. Maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.",
    "3Sum": "Given an integer array nums, return all the triplets <code>[nums[i], nums[j], nums[k]]</code> such that i != j, i != k, and j != k, and <code>nums[i] + nums[j] + nums[k] == 0</code>.",
    "Container With Most Water": "You are given an integer array <code>height</code> of length n. There are n vertical lines drawn such that the two endpoints of the i-th line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water.",
    "Product of Array Except Self": "Given an integer array <code>nums</code>, return an array answer such that <code>answer[i]</code> is equal to the product of all the elements of <code>nums</code> except <code>nums[i]</code>.",
    "Maximum Subarray": "Given an integer array <code>nums</code>, find the subarray with the largest sum, and return its sum.",
    "Find Minimum in Rotated Sorted Array": "Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array <code>nums</code> of unique elements, return the minimum element of this array. You must write an algorithm that runs in O(log n) time.",
    "Search in Rotated Sorted Array": "Given the array <code>nums</code> after the possible rotation and an integer <code>target</code>, return the index of <code>target</code> if it is in <code>nums</code>, or -1 if it is not in <code>nums</code>.",
    "Trapping Rain Water": "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
    "First Missing Positive": "Given an unsorted integer array <code>nums</code>, return the smallest missing positive integer. You must implement an algorithm that runs in O(n) time and uses constant extra space.",
    "Largest Rectangle in Histogram": "Given an array of integers <code>heights</code> representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
    "Median of Two Sorted Arrays": "Given two sorted arrays <code>nums1</code> and <code>nums2</code> of size m and n respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).",

    // Two Pointers
    "Reverse String": "Write a function that reverses a string. The input string is given as an array of characters <code>s</code>.",
    "Move Zeroes": "Given an integer array <code>nums</code>, move all 0's to the end of it while maintaining the relative order of the non-zero elements.",
    "Valid Palindrome": "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.",
    "Squares of a Sorted Array": "Given an integer array <code>nums</code> sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.",
    "Merge Sorted Array": "You are given two integer arrays <code>nums1</code> and <code>nums2</code>, sorted in non-decreasing order, and two integers m and n, representing the number of elements in nums1 and nums2 respectively. Merge <code>nums1</code> and <code>nums2</code> into a single array sorted in non-decreasing order.",
    "Remove Element": "Given an integer array <code>nums</code> and an integer <code>val</code>, remove all occurrences of <code>val</code> in <code>nums</code> in-place. The order of the elements may be changed.",
    "Two Sum II - Input Array Is Sorted": "Given a 1-indexed array of integers <code>numbers</code> that is already sorted in non-decreasing order, find two numbers such that they add up to a specific <code>target</code> number.",
    "Sort Colors": "Given an array <code>nums</code> with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.",
    "4Sum": "Given an array <code>nums</code> of n integers, return an array of all the unique quadruplets <code>[nums[a], nums[b], nums[c], nums[d]]</code> such that they add up to target.",
    "Valid Palindrome II": "Given a string s, return true if the s can be palindrome after deleting at most one character from it.",

    // Sliding Window
    "Maximum Average Subarray I": "You are given an integer array nums consisting of n elements, and an integer k. Find a contiguous subarray whose length is equal to k that has the maximum average value and return this value.",
    "Contains Duplicate II": "Given an integer array nums and an integer k, return true if there are two distinct indices i and j in the array such that nums[i] == nums[j] and abs(i - j) <= k.",
    "Longest Substring Without Repeating Characters": "Given a string s, find the length of the longest substring without repeating characters.",
    "Longest Repeating Character Replacement": "You are given a string s and an integer k. You can choose any character of the string and change it to any other uppercase English character. Return the length of the longest substring containing the same letter you can get after performing the above operations at most k times.",
    "Permutation in String": "Given two strings s1 and s2, return true if s2 contains a permutation of s1, or false otherwise.",
    "Find All Anagrams in a String": "Given two strings s and p, return an array of all the start indices of p's anagrams in s.",
    "Maximum Number of Vowels in a Substring": "Given a string s and an integer k, return the maximum number of vowel letters in any substring of s with length k.",
    "Fruit Into Baskets": "You are visiting a farm that has a single row of fruit trees arranged from left to right. You have two baskets, and each basket can only hold a single type of fruit. Return the maximum number of fruits you can pick.",
    "Max Consecutive Ones III": "Given a binary array nums and an integer k, return the maximum number of consecutive 1's in the array if you can flip at most k 0's.",
    "Minimum Window Substring": "Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t is included in the window. If there is no such substring, return the empty string.",
    "Sliding Window Maximum": "You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position. Return the max sliding window.",

    // Stack
    "Implement Stack using Arrays": "Design a stack class that supports push, pop, top, and retrieving the minimum element in constant time using an array.",
    "Valid Parentheses": "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
    "Min Stack": "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.",
    "Evaluate Reverse Polish Notation": "Evaluate the value of an arithmetic expression in Reverse Polish Notation. Valid operators are +, -, *, and /.",
    "Generate Parentheses": "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.",
    "Daily Temperatures": "Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature.",
    "Car Fleet": "There are n cars going to the same destination along a one-lane road. The destination is target miles away. Return the number of car fleets that will arrive at the destination.",
    "Asteroid Collision": "We are given an array asteroids of integers representing asteroids in a row. Find out the state of the asteroids after all collisions. If two asteroids meet, the smaller one will explode.",
    "Remove K Digits": "Given string num representing a non-negative integer num, and an integer k, return the smallest possible integer after removing k digits from num.",
    "Online Stock Span": "Design a class StockSpanner which collects daily price quotes for some stock and returns the span of that stock's price for the current day.",
    "Maximal Rectangle": "Given a rows x cols binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's and return its area.",

    // Binary Search
    "Binary Search Implementation": "Given an array of integers <code>nums</code> which is sorted in ascending order, and an integer <code>target</code>, write a function to search <code>target</code> in <code>nums</code>. If <code>target</code> exists, then return its index. Otherwise, return <code>-1</code>.",
    "Search Insert Position": "Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.",
    "Guess Number Higher or Lower": "We are playing the Guess Game. The game is as follows: I pick a number from 1 to n. You have to guess which number I picked.",
    "Search a 2D Matrix": "You are given an m x n integer matrix matrix with the following two properties: Each row is sorted in non-decreasing order. The first integer of each row is greater than the last integer of the previous row.",
    "Time Based Key-Value Store": "Design a time-based key-value data structure that can store multiple values for the same key at different time stamps and retrieve the key's value at a certain timestamp.",
    "Koko Eating Bananas": "Koko loves to eat bananas. There are n piles of bananas, the ith pile has piles[i] bananas. Return the minimum integer k such that she can eat all the bananas within h hours.",
    "Find First and Last Position of Element in Sorted Array": "Given an array of integers nums sorted in non-decreasing order, find the starting and ending position of a given target value.",
    "Capacity To Ship Packages Within D Days": "A conveyor belt has packages that must be shipped from one port to another within days days. Return the least weight capacity of the ship that will result in all the packages on the conveyor belt being shipped within days days.",
    "Split Array Largest Sum": "Given an integer array nums and an integer k, split nums into k non-empty subarrays such that the largest sum of any subarray is minimized.",
    "Find in Mountain Array": "You may recall that an array arr is a mountain array if and only if it is strictly increasing then strictly decreasing. Return the minimum index such that mountainArr.get(index) == target.",

    // Linked List
    "Print Linked List": "Given a linked list, write a function to print all the elements of the linked list.",
    "Reverse Linked List": "Given the head of a singly linked list, reverse the list, and return the reversed list.",
    "Merge Two Sorted Lists": "You are given the heads of two sorted linked lists list1 and list2. Merge the two lists in a one sorted list.",
    "Linked List Cycle": "Given head, the head of a linked list, determine if the linked list has a cycle in it.",
    "Reorder List": "You are given the head of a singly linked-list. Reorder the list such that nodes alternate from the front and back: L0 -> Ln -> L1 -> Ln-1 -> L2 -> Ln-2 -> ...",
    "Remove Nth Node From End of List": "Given the head of a linked list, remove the nth node from the end of the list and return its head.",
    "Copy List with Random Pointer": "A linked list of length n is given such that each node contains an additional random pointer, which could point to any node in the list, or null. Return a deep copy of the list.",
    "Add Two Numbers": "You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.",
    "Merge k Sorted Lists": "You are given an array of k linked-lists lists, each linked-list is sorted in ascending order. Merge all the linked-lists into one sorted linked-list and return it.",
    "Reverse Nodes in k-Group": "Given the head of a linked list, reverse the nodes of the list k at a time, and return the modified list.",

    // Trees DFS
    "Inorder Traversal": "Given the head of a binary tree, return the inorder traversal of its nodes' values.",
    "Maximum Depth of Binary Tree": "Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.",
    "Diameter of Binary Tree": "Given the root of a binary tree, return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree.",
    "Same Tree": "Given the roots of two binary trees p and q, write a function to check if they are the same or not.",
    "Subtree of Another Tree": "Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values of subRoot and false otherwise.",
    "Lowest Common Ancestor of a Binary Search Tree": "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.",
    "Kth Smallest Element in a BST": "Given the root of a binary search tree, and an integer k, return the kth smallest value (1-indexed) of all the values of the nodes in the tree.",
    "Construct Binary Tree from Preorder and Inorder Traversal": "Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.",
    "Validate Binary Search Tree": "Given the root of a binary tree, determine if it is a valid binary search tree (BST).",
    "Count Good Nodes in Binary Tree": "Given a binary tree root, a node X in the tree is named good if in the path from root to X there are no nodes with a value greater than X. Return the number of good nodes in the binary tree.",
    "Path Sum": "Given the root of a binary tree and an integer targetSum, return true if the tree has a root-to-leaf path such that adding up all the values along the path equals targetSum.",
    "Binary Tree Maximum Path Sum": "A path in a binary tree is a sequence of nodes where each pair of adjacent nodes in the sequence has an edge connecting them. A node can only appear in the sequence at most once. Note that the path does not need to pass through the root. Return the maximum path sum of any non-empty path.",
    "Serialize and Deserialize Binary Tree": "Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer... Design an algorithm to serialize and deserialize a binary tree.",

    // Trees BFS
    "Level Order Traversal": "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).",
    "Average of Levels in Binary Tree": "Given the root of a binary tree, return the average value of the nodes on each level in the form of an array.",
    "Symmetric Tree": "Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).",
    "Binary Tree Right Side View": "Given the root of a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.",
    "Populating Next Right Pointers in Each Node": "You are given a perfect binary tree where all leaves are on the same level, and every parent has two children. Populate each next pointer to point to its next right node. If there is no next right node, the next pointer should be set to NULL.",
    "Find Largest Value in Each Tree Row": "Given the root of a binary tree, return an array of the largest value in each row of the tree (0-indexed).",
    "Deepest Leaves Sum": "Given the root of a binary tree, return the sum of values of its deepest leaves.",
    "Minimum Number of Operations to Sort a Binary Tree by Level": "You are given the root of a binary tree with unique values. In one operation, you can choose any two nodes at the same level and swap their values. Return the minimum number of operations needed to make the values at each level sorted in a strictly increasing order.",

    // Graphs
    "BFS of Graph": "Given a directed graph. The task is to do Breadth First Traversal of this graph starting from 0.",
    "DFS of Graph": "Given a connected undirected graph. Perform a Depth First Traversal of the graph.",
    "Find if Path Exists in Graph": "There is a bi-directional graph with n vertices, where each vertex is labeled from 0 to n - 1. Return true if there is a valid path from source to destination, or false otherwise.",
    "Find Center of Star Graph": "There is an undirected star graph consisting of n nodes labeled from 1 to n. A star graph is a graph where there is one center node and exactly n - 1 edges that connect the center node with every other node. Return the center of the given star graph.",
    "Number of Islands": "Given an m x n 2D binary grid grid which represents a map of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically.",
    "Max Area of Island": "You are given an m x n binary matrix grid. An island is a group of 1's (representing land) connected 4-directionally (horizontal or vertical). You may assume all four edges of the grid are surrounded by water. The area of an island is the number of cells with a value 1 in the island. Return the maximum area of an island in grid. If there is no island, return 0.",
    "Clone Graph": "Given a reference of a node in a connected undirected graph. Return a deep copy (clone) of the graph.",
    "Pacific Atlantic Water Flow": "There is an m x n rectangular island that borders both the Pacific Ocean and Atlantic Ocean. The Pacific Ocean touches the island's left and top edges, and the Atlantic Ocean touches the island's right and bottom edges. Return a list of grid coordinates result where result[i] = [ri, ci] denotes that rain water can flow from cell (ri, ci) to both the Pacific and Atlantic oceans.",
    "Surrounded Regions": "Given an m x n matrix board containing 'X' and 'O', capture all regions that are 4-directionally surrounded by 'X'. A region is captured by flipping all 'O's into 'X's in that surrounded region.",
    "Rotting Oranges": "You are given an m x n grid where each cell can have one of three values: 0 representing an empty cell, 1 representing a fresh orange, or 2 representing a rotten orange. Every minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten. Return the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.",
    "Course Schedule": "There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return true if you can finish all courses. Otherwise, return false.",
    "Redundant Connection": "In this problem, a tree is an undirected graph that is connected and has no cycles. You are given a graph that started as a tree with n nodes labeled from 1 to n, with one additional edge added. The added edge has two different vertices chosen from 1 to n, and was not an edge that already existed. The graph is represented as an array edges of length n where edges[i] = [ai, bi] indicates that there is an edge between nodes ai and bi in the graph. Return an edge that can be removed so that the resulting graph is a tree of n nodes.",
    "Word Ladder": "A transformation sequence from word beginWord to word endWord using a dictionary wordList is a sequence of words beginWord -> s1 -> s2 -> ... -> sk such that: Every adjacent pair of words differs by a single letter. Every si for 1 <= i <= k is in wordList. Note that beginWord does not need to be in wordList. sk == endWord. Given two words, beginWord and endWord, and a dictionary wordList, return the number of words in the shortest transformation sequence from beginWord to endWord, or 0 if no such sequence exists.",
    "Alien Dictionary": "There is a new alien language that uses the English alphabet. However, the order of the letters is unknown to you. You are given a list of strings words from the alien language's dictionary. Now it is claimed that the strings in words are sorted lexicographically by the rules of this new language. If this claim is incorrect, and the given arrangement of string in words cannot correspond to any order of letters, return \"\". Otherwise, return a string of the unique letters in the new alien language sorted in lexicographically increasing order by the new language's rules. If there are multiple solutions, return any of them."
};
