spring.datasource.url=jdbc:mysql://localhost:3306/springboot_db
spring.datasource.username=root
spring.datasource.password=pratham@sahil2978

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Generative AI Configuration
gemini.api.key=AIzaSyAFxKGFMFIOEQEEqszptsMzyW0jYlfYR0A

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/schema.sql
